In [3]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [4]:
import pandas as pd
import numpy as np 

In [5]:
np.add(1.0,4.0)

5.0

In [11]:
x1 = np.arange(9.0).reshape((3,3))
x2 = np.arange(3.0)
np.add(x1,x2)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [15]:
a = [1, 2, 3]
b = [2, 3, 4]
c = np.multiply(a,b)

In [13]:
c

array([ 2,  6, 12])

In [20]:
#Split ()
#returns a list of the words in the string ,using separator deliiter
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 2)


In [21]:
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [26]:
#join()  
# returns  a string is the concatenaton of the string in the sequence

arr1 =  np.array([1, 2, 3, 9])
arr2 = np.array([4, 5, 6])
arr3 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2, arr3))
print(np.sort(arr))

[1 2 3 4 4 5 5 6 6 9]


In [32]:
#encode()
#class str.encode element-wise

x = np.array(['aAaAaA', 'aA', 'abBABab'])
print("x:", x)

x: ['aAaAaA' 'aA' 'abBABab']


In [34]:
e = np.char.encode(x, encoding='cp037')
e

array([b'\x81\xc1\x81\xc1\x81\xc1', b'\x81\xc1',
       b'\x81\x82\xc2\xc1\xc2\x81\x82'], dtype='|S7')

In [35]:
d = np.char.decode(e, encoding='cp037')
d

array(['aAaAaA', 'aA', 'abBABab'], dtype='<U7')

In [36]:
# Assuming you have a byte string encoded in cp037
encoded_data = b'\x83\x84\x88\x89\x93\x94\x99\x9a'

# Decode using cp037
decoded_data = encoded_data.decode('cp037')

print(decoded_data)

cdhilmrª


In [37]:
# function for rounding
#numpy.around().
np.around([.5, 1.5, 2.5,3.5,4.5]) # round to nearest even value


array([0., 2., 2., 4., 4.])

In [41]:
#numpy.floor()
#this function returns the largest intger not greater then the input parameter 
# note - In python ,flooring always is rounded away from  0

a = np.array([-1.0, -1.9, -0.9, 0.2,1.8,1.9,2.0])
np.floor(a)


array([-1., -2., -1.,  0.,  1.,  1.,  2.])

In [42]:
#nupay.ceil()
# The ceil() funciton returns the ceiling of an input value ,i.e the ceil of the scalar x is the smallest integer i,such that I >= x

a = np.array([-1.7,-1.5, -0.2,0.2,1.5,1.7,2.0])
np.ceil(a)


array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [58]:
#numpy.round()
#Round an array to the givennumber of dicimals.
# it take the decimal value of first number with given limtes in right side of the value 
import numpy as np 
np.round(344534565464.15199, 4)


344534565464.152

In [59]:
#numpy.fix()
np.fix([2.1,2.9,-2.1,-2.9])

array([ 2.,  2., -2., -2.])

In [61]:
#numpy.trunc()
a = np.array([-1.7,-1.5,-0.2,0.2,1.5,1.7,2.0])
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])

In [62]:
# arthimitical funcitons
#numpy.reciprocal()

#numpy.reciprocal()
#This function returns the reciprocal of argument, element-wise. For elements with absolute values larger than 1, the
#result is always 0 because of the way in which Python handles integer division.
np.reciprocal([1,2.,3.33])


array([1.       , 0.5      , 0.3003003])

In [64]:
#numpy.power()
#This function treats elements in the first input array as base and returns it raised to the power of the corresponding
#element in the second input array
x1 = np.arange(6)
x1


array([0, 1, 2, 3, 4, 5])

In [69]:
np.power(x1,3)


array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [68]:
np.power(x1,2)

array([ 0,  1,  4,  9, 16, 25], dtype=int32)

In [70]:
np.power(x1,4)

array([  0,   1,  16,  81, 256, 625], dtype=int32)

In [71]:
# numpy.mod()
#This function returns the remainder of division of the corresponding elements in the input array. The
#function numpy.remainder() also produces the same result.
np.remainder([4,7], [2,3])

array([0, 1])

In [72]:
#Trigonometric functions:
#numpy.sin()
#Trigonometric sine, element-wise
np.sin(np.pi/2.)

1.0

In [74]:
np.sin(np.pi)

1.2246467991473532e-16

In [75]:
np.cos(np.array([0,np.pi/2,np.pi]))

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])