In [1]:
a = ["one", 1, "two", "3", 4]

In [2]:
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: one
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


In [3]:
import numpy as np 

In [4]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [5]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [6]:
print(np.__version__)


1.21.5


In [7]:
# Check the type of the array

type(a)

numpy.ndarray

In [8]:
a.dtype

dtype('int32')

In [9]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

# Enter your code here

In [10]:
a=np.array([-1,1])
b=np.array([1,1])
np.dot(a,b) 

0

In [11]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out


array([1, 2])

In [13]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])