In [1]:
#Data manipulations #
#melt(frame[,id_vars,valus_vars,var_name,...])
#unpivot a dataframe from wide to long format ,optionally leaving identifiers set 

import pandas as pd

df = pd.DataFrame({'A' : {0:'a',1:'b',2:'c'},
                   'B' : {0: 1, 1: 3, 2: 5},
                   'C' : {0: 2, 1: 4, 2: 6}})

In [2]:
df

A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

In [3]:
pd.melt(df,id_vars=['A'], value_vars=['B'])

A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

In [4]:
# pivot(data[,index,columns,values]) 
#return reshaped DataFrame organized by given index /column values 
df = pd.DataFrame({'foo': ['one','one','one' ,'two','two','two'],
                    'bar': ['A','B','C','A','B','C'],
                    'baz': [1,2,3,4,5,6],
                    'zoo':['x','y','z','q','w','t']})


In [5]:
df

foo bar  baz zoo
0  one   A    1   x
1  one   B    2   y
2  one   C    3   z
3  two   A    4   q
4  two   B    5   w
5  two   C    6   t

In [6]:
df.pivot(index='foo',columns='bar',values='baz')

bar  A  B  C
foo         
one  1  2  3
two  4  5  6

In [7]:
import pandas as pd


In [8]:
# Create a sample DataFrame
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Value': [10, 20, 30, 40, 50, 60]
}

In [9]:
df = pd.DataFrame(data)

In [10]:
df

Category  Value
0        A     10
1        B     20
2        A     30
3        B     40
4        A     50
5        B     60

In [11]:
# Display the original DataFrame
print("Original DataFrame:")
print(df)


Original DataFrame:
  Category  Value
0        A     10
1        B     20
2        A     30
3        B     40
4        A     50
5        B     60


In [12]:
# Use pivot to reshape the DataFrame
pivot_df = df.pivot(columns='Category', values='Value')

In [13]:
pivot_df

Category     A     B
0         10.0   NaN
1          NaN  20.0
2         30.0   NaN
3          NaN  40.0
4         50.0   NaN
5          NaN  60.0

In [14]:
# Display the pivoted DataFrame
print("\nPivoted DataFrame:")
print(pivot_df)


Pivoted DataFrame:
Category     A     B
0         10.0   NaN
1          NaN  20.0
2         30.0   NaN
3          NaN  40.0
4         50.0   NaN
5          NaN  60.0


In [15]:
#TOP level Missing Data
#isna(obj) 
#Detect missing vlues for an array-like object
import numpy as np
array = np.array([[1,np.nan,3],[4,5,np.nan]])


In [16]:
array

array([[ 1., nan,  3.],
       [ 4.,  5., nan]])

In [17]:
pd.isna(array)

array([[False,  True, False],
       [False, False,  True]])

In [18]:
#isnull(obj)
#detect missing values for an array-like object
import pandas as pd
df = pd.DataFrame([['ant','bee','cat'],['dog',None,'fly']])
df 

0     1    2
0  ant   bee  cat
1  dog  None  fly

In [19]:
pd.isnull(df)

0      1      2
0  False  False  False
1  False   True  False

In [20]:
#notna(obj)
#detect non missing values for an array-like object
array = np.array([[1,np.nan,3],[4,5,np.nan]])
array 

array([[ 1., nan,  3.],
       [ 4.,  5., nan]])

In [21]:
pd.notna(array)

array([[ True, False,  True],
       [ True,  True, False]])

In [22]:
import pandas as pd

In [23]:
# Create a sample DataFrame
data = {
    'A': ['1', '2', '3', '4', '5'],
    'B': ['10', '20', '30', '40', '50']
}

In [24]:
df = pd.DataFrame(data)

In [25]:
# Display the original DataFrame
df

A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [26]:
# Use to_numeric to convert columns to numeric
df['A'] = pd.to_numeric(df['A'])
df['B'] = pd.to_numeric(df['B'])

In [27]:
# Display the DataFrame after conversion 
df

A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [31]:
#DATE RANGE date_range([start,end,periods.freq,tz,...])
#returns a fixed frequency Datetime Index 
date_range = pd.date_range(start='2023-01-01', end='2023-09-10')

print(date_range)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-01', '2023-09-02', '2023-09-03', '2023-09-04',
               '2023-09-05', '2023-09-06', '2023-09-07', '2023-09-08',
               '2023-09-09', '2023-09-10'],
              dtype='datetime64[ns]', length=253, freq='D')


In [32]:
date_range = pd.date_range(start='2023-01-01', end='2023-09-10')

print(date_range)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-01', '2023-09-02', '2023-09-03', '2023-09-04',
               '2023-09-05', '2023-09-06', '2023-09-07', '2023-09-08',
               '2023-09-09', '2023-09-10'],
              dtype='datetime64[ns]', length=253, freq='D')


In [34]:
date_range = pd.date_range(start='2024-04-21', end='2024-04-24')
day_names = date_range.day_name()
date_and_day = pd.DataFrame({ 'Day': day_names   ,'Date': date_range})
print(date_and_day)

         Day       Date
0     Sunday 2024-04-21
1     Monday 2024-04-22
2    Tuesday 2024-04-23
3  Wednesday 2024-04-24


In [36]:
a = [2, 3,4,5]
b = np.array(a)
print(b)

[2 3 4 5]


In [37]:
c = np.array(b)
print(c)

[2 3 4 5]
