In [98]:
np.random.seed(5)
print("Random number generation(form uniform distribution): ")
print(np.random.rand(10,7))

Random number generation(form uniform distribution): 
[[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386
  0.76590786]
 [0.51841799 0.2968005  0.18772123 0.08074127 0.7384403  0.44130922
  0.15830987]
 [0.87993703 0.27408646 0.41423502 0.29607993 0.62878791 0.57983781
  0.5999292 ]
 [0.26581912 0.28468588 0.25358821 0.32756395 0.1441643  0.16561286
  0.96393053]
 [0.96022672 0.18841466 0.02430656 0.20455555 0.69984361 0.77951459
  0.02293309]
 [0.57766286 0.00164217 0.51547261 0.63979518 0.9856244  0.2590976
  0.80249689]
 [0.87048309 0.92274961 0.00221421 0.46948837 0.98146874 0.3989448
  0.81373248]
 [0.5464565  0.77085409 0.48493107 0.02911156 0.08652569 0.11145381
  0.25124511]
 [0.96491529 0.63176605 0.8166602  0.566082   0.63535621 0.81190239
  0.92668262]
 [0.91262676 0.82481072 0.09420273 0.36104842 0.03550903 0.54635835
  0.79614272]]


In [96]:
#Random number generation
import numpy as np


In [97]:
print("Numbers from normal distribution with zero mena and standerd deviation 1 i.e standerd normal:")
print(np.random.randn(10,3))

Numbers from normal distribution with zero mena and standerd deviation 1 i.e standerd normal:
[[-1.15245668  0.60585079 -1.45095264]
 [ 0.33678691  0.15925172  0.16655069]
 [-0.69249262  0.58531776 -2.05366068]
 [ 0.55055514 -0.44652824 -0.60047848]
 [ 0.83084731 -0.26158377 -0.45608588]
 [ 0.96081056 -0.44173663  0.44613649]
 [ 0.63035595 -1.033613    1.44303152]
 [-1.34199885 -0.07487068 -0.96394042]
 [ 0.80141811 -2.05366369  1.66982846]
 [-0.15813881  0.1932608  -1.12585155]]


In [41]:
print("Random Integer Vector:",np.random.randint(5,20,10))


Random Integer Vector: [ 8 19 13 15 10 15 10  9  8 19]


In [42]:
print("Random Integer Vector:",np.random.randint(5,20,10))

Random Integer Vector: [15 14 10 14 11 14 10  6 19  6]


In [43]:
print("\nRandom integer matrix")
print(np.random.randint(1,30,(6,7)))


Random integer matrix
[[ 1 29  9 15  1 14  6]
 [27 10 20 29 12  4 17]
 [20 24  4 24  4  3 23]
 [ 7 19 16  8  1  4 29]
 [24  6  2 28  7 28  8]
 [ 4 15 10  8 26 27  8]]


In [46]:
a = np.random.randint(2,40,(10,10))
a

array([[27, 11, 33, 24, 18, 17, 17, 33, 15, 19],
       [37, 21, 30, 21, 23, 18, 34, 28, 32, 32],
       [31, 16, 16, 36, 10, 19, 12,  8, 11, 31],
       [35, 26, 20, 22, 27,  7, 14, 17, 26, 14],
       [ 3,  7, 19, 13, 26, 21, 28, 25, 10, 12],
       [ 5,  6, 32, 32, 33, 28, 34, 15, 14, 21],
       [12, 35, 39, 35,  2, 38,  2, 10, 26, 28],
       [ 7, 31, 20, 14,  8, 23,  4, 24, 33, 14],
       [ 7, 17, 24, 20, 33, 39, 20, 38, 38,  5],
       [11,  2, 10, 19,  2, 27, 38, 16,  7, 15]])

In [48]:
np.clip(a,a_min=5,a_max=25)

array([[25, 11, 25, 24, 18, 17, 17, 25, 15, 19],
       [25, 21, 25, 21, 23, 18, 25, 25, 25, 25],
       [25, 16, 16, 25, 10, 19, 12,  8, 11, 25],
       [25, 25, 20, 22, 25,  7, 14, 17, 25, 14],
       [ 5,  7, 19, 13, 25, 21, 25, 25, 10, 12],
       [ 5,  6, 25, 25, 25, 25, 25, 15, 14, 21],
       [12, 25, 25, 25,  5, 25,  5, 10, 25, 25],
       [ 7, 25, 20, 14,  8, 23,  5, 24, 25, 14],
       [ 7, 17, 24, 20, 25, 25, 20, 25, 25,  5],
       [11,  5, 10, 19,  5, 25, 25, 16,  7, 15]])

In [64]:
b = np.random.randint(2,40,10)
b

array([20, 13, 32, 31, 35, 32, 31, 31, 23,  8])

In [65]:
np.clip(b, a_min=5, a_max=25)

array([20, 13, 25, 25, 25, 25, 25, 25, 23,  8])

In [62]:
#it gives index details 
print(np.where(a < 10))

(array([2, 3, 4, 4, 5, 5, 6, 6, 7, 7, 7, 8, 8, 9, 9, 9], dtype=int64), array([7, 5, 0, 1, 0, 1, 4, 6, 0, 4, 6, 0, 9, 1, 4, 8], dtype=int64))


In [67]:
#find the data existes in the array 
print(np.where(a == 10))

(array([2, 4, 6, 9], dtype=int64), array([4, 8, 7, 2], dtype=int64))


In [70]:
import numpy as np
from numpy.random import randint as rint
a = rint(1,99,20)
a

array([17, 16, 84, 92, 71, 72, 42, 14, 62,  1, 47, 66, 87, 81, 49,  4, 78,
       61, 17, 12])

b = a.reshape(2,2,4)
b 

In [79]:
print("Min of a :",b.main())

AttributeError: 'numpy.ndarray' object has no attribute 'main'

In [84]:
#sorting
M = rint(1,100,25).reshape(5,5)
M

array([[82, 21, 87,  2, 75],
       [71, 49, 56, 52, 98],
       [40,  1, 31, 43, 88],
       [72,  5, 63, 26, 18],
       [51, 64, 18, 74,  2]])

In [85]:
print("n5x5 Matrix of random integers \n",'_'*50,"\n",M)

n5x5 Matrix of random integers 
 __________________________________________________ 
 [[82 21 87  2 75]
 [71 49 56 52 98]
 [40  1 31 43 88]
 [72  5 63 26 18]
 [51 64 18 74  2]]


In [86]:
print("n5x5 sorted Matrix of random integers along with each row  \n",'_'*50,"\n",np.sort(M)) #Default axis = 1

n5x5 sorted Matrix of random integers along with each row  
 __________________________________________________ 
 [[ 2 21 75 82 87]
 [49 52 56 71 98]
 [ 1 31 40 43 88]
 [ 5 18 26 63 72]
 [ 2 18 51 64 74]]


In [89]:
print("sorted Matrix of random integers along with each row  \n",'_'*50,"\n",np.sort(M, axis=0)) #Default axis = 1

sorted Matrix of random integers along with each row  
 __________________________________________________ 
 [[40  1 18  2  2]
 [51  5 31 26 18]
 [71 21 56 43 75]
 [72 49 63 52 88]
 [82 64 87 74 98]]


In [91]:
print("n5x5 Matrix of random integers \n",'_'*50,"\n",M)
print("n5x5 sorted Matrix of random integers along with each row  \n",'_'*50,"\n",np.sort(M)) #Default axis = 1
print("sorted Matrix of random integers along with each colum  \n",'_'*50,"\n",np.sort(M, axis=0)) #Default axis = 1

n5x5 Matrix of random integers 
 __________________________________________________ 
 [[82 21 87  2 75]
 [71 49 56 52 98]
 [40  1 31 43 88]
 [72  5 63 26 18]
 [51 64 18 74  2]]
n5x5 sorted Matrix of random integers along with each row  
 __________________________________________________ 
 [[ 2 21 75 82 87]
 [49 52 56 71 98]
 [ 1 31 40 43 88]
 [ 5 18 26 63 72]
 [ 2 18 51 64 74]]
sorted Matrix of random integers along with each colum  
 __________________________________________________ 
 [[40  1 18  2  2]
 [51  5 31 26 18]
 [71 21 56 43 75]
 [72 49 63 52 88]
 [82 64 87 74 98]]


In [92]:
my_mat = [[1,2,3],[1,2,4],[5,6,7]]

In [93]:
mat = np.array(my_mat)

In [94]:
mat

array([[1, 2, 3],
       [1, 2, 4],
       [5, 6, 7]])

In [95]:
print("\n Double backet index ")
print("elements in row index 1 and column index 2:",mat[:,1:])


 Double backet index 
elements in row index 1 and column index 2: [[2 3]
 [2 4]
 [6 7]]
